name: general
channels:
  - conda-forge
  - defaults
dependencies:
# General dependencies
  - python=3.12
  - numpy
  - pandas
  - fastai::opencv-python-headless
  - pillow
  - dask
  - tqdm
  - pyarrow
  - mlflow
  - pyyaml
# additional dependencies